# permissions for end users to edit stacks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: stack-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: application
    app.kubernetes.io/part-of: application
    app.kubernetes.io/managed-by: kustomize
  name: stack-editor-role
rules:
- apiGroups:
  - application.ksctl.com
  resources:
  - stacks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - application.ksctl.com
  resources:
  - stacks/status
  verbs:
  - get
