---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - storage.ksctl.com
  resources:
  - importstates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.ksctl.com
  resources:
  - importstates/finalizers
  verbs:
  - update
- apiGroups:
  - storage.ksctl.com
  resources:
  - importstates/status
  verbs:
  - get
  - patch
  - update
