name: release-ksctl-agent-ghcr
on:
  push:
    paths:
    - 'internal/**'
    - 'pkg/**'
    - 'go.mod'
    - 'go.sum'
    - 'build/**'
    - 'build/agent/**'
    - 'ksctl-components/agent/**'
    branches: [ main ]
  # pull_request:
  #   paths:
  #     - 'internal/**'
  #     - 'pkg/**'
  #     - 'build/**'
  #     - 'ksctl-agent/**'
  #     - 'Makefile'
  #   branches: [ main ]
  #   types: [ labeled, opened, synchronize, reopened ]

jobs:
  ksctl-agent:
    runs-on: ubuntu-latest
 
    permissions:
      packages: write
      contents: read
 
    steps:
      - name: Checkout
        uses: actions/checkout@v3
 
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
 
      - name: Build Inventory Image
        run: |
          docker build --file build/agent/Dockerfile --tag ghcr.io/ksctl/ksctl:agent-latest .
          docker push ghcr.io/ksctl/ksctl:agent-latest