name: e2e for ksctl

on:
  workflow_dispatch:
  workflow_call:

jobs:
  setup:
    env:
      PS4: '+\[\033[0;33m\](\[\033[0;36m\]${BASH_SOURCE##*/}:${LINENO}\[\033[0;33m\])\[\033[0m\] '

    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [svr-1, svr-2]
    steps:
      - name: remove the .ksctl
        run: |
          rm -rf ${HOME}/.ksctl

  builder:
    environment: runners
    env:
      PS4: '+\[\033[0;33m\](\[\033[0;36m\]${BASH_SOURCE##*/}:${LINENO}\[\033[0;33m\])\[\033[0m\] '
      SSH_USER_SVR: ${{secrets.SSH_USER_SVR}}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "stable"
      - name: building amd64 binary
        working-directory: test/e2e
        run: |
          GOOS="linux" GOARCH="amd64" go build -v -o ksctl-e2e-amd64 .

      - name: ssh setup
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_HOST_SVR_1: ${{secrets.SSH_HOST_SVR_1}}
          SSH_HOST_SVR_2: ${{secrets.SSH_HOST_SVR_2}}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 400 ~/.ssh/id_ed25519
          cat <<EOF > ~/.ssh/config
          Host server_1
              HostName $SSH_HOST_SVR_1
              User $SSH_USER_SVR
              IdentityFile ~/.ssh/id_ed25519
              StrictHostKeyChecking no
          Host server_2
              HostName $SSH_HOST_SVR_2
              User $SSH_USER_SVR
              IdentityFile ~/.ssh/id_ed25519
              StrictHostKeyChecking no
          EOF

      - name: transfer binary to svr-1
        working-directory: test/e2e
        run: |
          rsync -vzh ./ksctl-e2e-amd64 server_1:/home/$SSH_USER_SVR/actions-runner/ksctl-bin/

      - name: transfer binary to svr-2
        working-directory: test/e2e
        run: |
          rsync -vzh ./ksctl-e2e-amd64 server_2:/home/$SSH_USER_SVR/actions-runner/ksctl-bin/

  local-e2e:
    uses: ./.github/workflows/e2e-local.yml
    needs: ["setup"]
    secrets: inherit

  civo-e2e:
    uses: ./.github/workflows/e2e-civo.yml
    needs: ["setup"]
    secrets: inherit

  azure-e2e:
    uses: ./.github/workflows/e2e-azure.yml
    needs: ["setup"]
    secrets: inherit

  aws-e2e:
    uses: ./.github/workflows/e2e-aws.yml
    needs: ["setup"]
    secrets: inherit

  notification:
    runs-on: e2e
    environment: e2e
    env:
      PS4: '+\[\033[0;33m\](\[\033[0;36m\]${BASH_SOURCE##*/}:${LINENO}\[\033[0;33m\])\[\033[0m\] '
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      RED: 16711680
      GREEN: 65280
      BLUE: 255
      DISCORD_TITLE: "e2e Workflow Summary"
      GITHUB_RUN: ${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}

    if: always()
    needs: [local-e2e, azure-e2e, civo-e2e, aws-e2e]
    steps:
      - name: Discord
        run: |
          set -xe
          local_status=$(echo "${{ needs.local-e2e.result }}")
          azure_status=$(echo "${{ needs.azure-e2e.result }}")
          civo_status=$(echo "${{ needs.civo-e2e.result }}")
          aws_status=$(echo "${{ needs.aws-e2e.result }}")


          if [[ $local_status == "failure" || $azure_status == "failure" || $civo_status == "failure" || $aws_status == "failure" ]]; then
            SUMMARY='### FAILURE :warning:'

            if [[ $local_status == "failure" ]]; then
              SUMMARY+='\n- Local-Kind'
            fi

            if [[ $azure_status == "failure" ]]; then
              SUMMARY+='\n- Azure'
            fi

            if [[ $civo_status == "failure" ]]; then
              SUMMARY+='\n- Civo'
            fi

            if [[ $aws_status == "failure" ]]; then
              SUMMARY+='\n- AWS'
            fi

            curl --fail \
              -X POST \
              -H "Content-Type: application/json" \
              -d "{\"embeds\": [{ \"title\": \"${DISCORD_TITLE}\", \"description\": \"${SUMMARY}\", \"url\": \"${GITHUB_RUN}\", \"color\": $RED, \"timestamp\": \"$(date -u +"%Y-%m-%dT%H:%M:%SZ")\", \"footer\": {\"text\": \"no bots were harmed\"}, \"author\": {\"name\": \"github actions\" } }]}" \
              $DISCORD_WEBHOOK_URL

          else
            SUMMARY='### SUCCESSFUL :rocket:'

            curl --fail \
              -X POST \
              -H "Content-Type: application/json" \
              -d "{\"embeds\": [{ \"title\": \"${DISCORD_TITLE}\", \"description\": \"${SUMMARY}\", \"url\": \"${GITHUB_RUN}\", \"color\": $GREEN, \"timestamp\": \"$(date -u +"%Y-%m-%dT%H:%M:%SZ")\", \"footer\": {\"text\": \"no bots were harmed\"}, \"author\": {\"name\": \"github actions\" } }]}" \
              $DISCORD_WEBHOOK_URL
          fi
